### ISSUE TITLE
Add Appimage to the build artifacts

### ISSUE THREAD

**Issue by flux242** [ExpressLRS/ExpressLRS-Configurator#587]
this recipe `expresslrs-configurator.yml` file (based on focal) will create an Appimage from a `expresslrs-configurator_1.6.1_amd64.deb`  package:

```
# You can easily make your own using this recipe like this on a Debian/Ubuntu system:
# wget -c "https://github.com/AppImage/AppImages/raw/master/pkg2appimage"
# bash -ex pkg2appimage expresslrs-configurator.yml

app: expresslrs-configurator

ingredients:
  dist: focal
  sources: 
    - deb http://us.archive.ubuntu.com/ubuntu/ focal main universe
  debs:
    - "$(pwd)"/expresslrs-configurator_1.6.1_amd64.deb
script:
  - cat > ./AppRun <<\HEREDOC
  - #!/bin/sh
  - HERE=$(dirname $(readlink -f "${0}"))
  - export LD_LIBRARY_PATH="${HERE}"/usr/lib:$PATH
  - exec ${HERE}/opt/ExpressLRS\ Configurator/expresslrs-configurator "$@"
  - HEREDOC
  - chmod a+x ./AppRun
  - cp ./usr/share/icons/hicolor/48x48/apps/expresslrs-configurator.png expresslrs-configurator.png
```
